# version: '3.8'
services:
  order-backend:
    hostname: order-backend-${GITHUB_USER}
    environment:
      - GITHUB_USER=${GITHUB_USER}
    build:
      context: .
      dockerfile: ./order-backend/Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
    image: shop/order-backend:latest
    depends_on:
      - order-quotes
    ports:
      - "54040:54040"
      - "54041:54041"
    networks:
      - app-network

  order-api:
    hostname: order-api-${GITHUB_USER}
    environment:
      - GITHUB_USER=${GITHUB_USER}
    build:
      context: .
      dockerfile: ./order-api/Dockerfile
      args:
        DT_CODE_MODULE: "${DT_ENVIRONMENT_HOST}/linux/oneagent-codemodules:java"
        GITHUB_USER: ${GITHUB_USER}
    image: shop/order-api:latest
    entrypoint: ["sh", "-c", "java -jar order-api-${GITHUB_USER}.jar"]
    depends_on:
      - order-backend
    ports:
      - "54039:54039"
    networks:
      - app-network

  order-quotes:
    hostname: order-quotes-${GITHUB_USER}
    environment:
      - GITHUB_USER=${GITHUB_USER}
    build:
      context: .
      dockerfile: ./order-quotes/Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
    image: shop/order-quotes:latest
    depends_on:
      - opentelemetry-collector
    ports:
      - "8090:8090"
    networks:
      - app-network

  loadgen:
    environment:
      - GITHUB_USER=${GITHUB_USER}
    build:
      context: .
      dockerfile: ./loadgen/Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
    image: shop/loadgen:latest
    depends_on:
      - order-api
    networks:
      - app-network

  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    environment:
      - ENVIRONMENT_ID=${ENVIRONMENT_ID}
      - DT_API_TOKEN=${DT_API_TOKEN}    
    container_name: opentelemetry-collector
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55680:55680"
    command: --config /etc/otel-collector-config.yaml      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge